# block types
PARAGRAPH = "paragraph"
HEADING_2 = "heading_2"
TOGGLE = "toggle"
BULLETED_LIST_ITEM = "bulleted_list_item"

BLOCK_TYPES = [PARAGRAPH, HEADING_2, TOGGLE, BULLETED_LIST_ITEM]
SUB_BLOCKS = [BULLETED_LIST_ITEM]